require('nvim-treesitter.configs').setup({
    ensure_installed = {
        "bash",
        "c",
        "cpp",
        "css",
        "elixir",
        "fish",
        "graphql",
        "html",
        "javascript",
        "json",
        "lua",
        "markdown",
        "markdown_inline",
        "php",
        "python",
        "regex",
        "ruby",
        "rust",
        "scss",
        "sql",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "yaml",
        "terraform",
        "lua",
        "vim",
        "go",
        "http",
        "diff",
    },
    highlight = {
        enable = true,
    },
    indent = {
        enable = true,
    },
    modules = {},
    ignore_install = { "javascript" },
    auto_install = true,
    sync_install = false,
    autotag = {
        enable = true,
        filetypes = {
            "html",
            "javascript",
            "javascriptreact",
            "svelte",
            "typescript",
            "typescriptreact",
            "vue",
            "xml",
        },
    },
})
